require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/100yrs/code-style-guides/master/linters/rubocop/rubocop.yml

AllCops:
  TargetRubyVersion: 3.3

Rails:
  Enabled: true
