# frozen_string_literal: true

source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "~> 7.1.3.2"
gem "puma", "~> 6.0"
gem "sqlite3"
gem 'propshaft'
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "lookbook", "~> 2.0"

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

gem "pulse_view_components", path: "../"

group :development, :test do
  gem "foreman"
end

group :development do
  gem "listen"
  gem "web-console", ">= 4.1.0"
end
